import type { Metadata } from "next";
import { Shippori_Mincho, Sue_Ellen_Francisco, Work_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import TopNav from "@/components/TopNav";


const shipporiMincho = Shippori_Mincho({
  subsets: ['latin'],
  weight: ['400', '600', '800'],
  display: 'swap',
  variable: '--font-shippori-mincho'
});
const workSans = Work_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '800'],
  display: 'swap',
  variable: '--font-work-sans',
});
const sueEllen = Sue_Ellen_Francisco({
  subsets: ['latin'],
  weight: ['400'],
  display: 'swap',
  variable: '--font-sue-ellen'
})




export const metadata: Metadata = {
  title: {
    default: "Humanity Charity",
    template: "%s | Humanity Charity",
  },
  description: "Welcome to Humanity Charity Foundation"
  
  // title: "Create Next App",

  // description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${shipporiMincho.variable} ${workSans.variable} ${sueEllen.variable}`}>
      <body>
        <TopNav />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
